import React from "react"
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
  },
  title: {
    fontSize: 20,
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "bold",
  },
  section: {
    marginBottom: 15,
  },
  label: {
    fontSize: 10,
    color: "#666",
    marginBottom: 5,
  },
  value: {
    fontSize: 12,
    marginBottom: 10,
  },
  divider: {
    borderBottom: "1px solid #e5e7eb",
    marginVertical: 15,
  },
  disclaimer: {
    fontSize: 8,
    color: "#999",
    marginTop: 30,
    padding: 10,
    backgroundColor: "#f3f4f6",
    fontStyle: "italic",
  },
  header: {
    marginBottom: 30,
  },
})

type TenancyAgreementProps = {
  propertyAddress: string
  propertyPostcode: string
  tenantName: string
  landlordName: string
  startDate: string
  endDate: string | null
  monthlyRent: number
  depositAmount: number | null
  depositProtectionScheme: string | null
}

export const TenancyAgreementPDF = ({
  propertyAddress,
  propertyPostcode,
  tenantName,
  landlordName,
  startDate,
  endDate,
  monthlyRent,
  depositAmount,
  depositProtectionScheme,
}: TenancyAgreementProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>ASSURED SHORTHOLD TENANCY AGREEMENT</Text>
      </View>

      <View style={styles.disclaimer}>
        <Text>
          <Text style={{ fontWeight: "bold" }}>DISCLAIMER:</Text> This is a template document generated by LandlordLens. 
          It is not a substitute for professional legal advice. Please consult with a qualified solicitor or legal 
          professional before using this document. LandlordLens does not provide legal advice and accepts no liability 
          for the use of this template.
        </Text>
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.label}>PROPERTY ADDRESS</Text>
        <Text style={styles.value}>
          {propertyAddress}, {propertyPostcode}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>LANDLORD</Text>
        <Text style={styles.value}>{landlordName}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>TENANT</Text>
        <Text style={styles.value}>{tenantName}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.label}>TENANCY START DATE</Text>
        <Text style={styles.value}>
          {new Date(startDate).toLocaleDateString("en-GB", {
            weekday: "long",
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>
      </View>

      {endDate && (
        <View style={styles.section}>
          <Text style={styles.label}>TENANCY END DATE</Text>
          <Text style={styles.value}>
            {new Date(endDate).toLocaleDateString("en-GB", {
              weekday: "long",
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </Text>
        </View>
      )}

      <View style={styles.section}>
        <Text style={styles.label}>MONTHLY RENT</Text>
        <Text style={styles.value}>£{monthlyRent.toLocaleString("en-GB", { minimumFractionDigits: 2 })} per month</Text>
      </View>

      {depositAmount && (
        <View style={styles.section}>
          <Text style={styles.label}>DEPOSIT</Text>
          <Text style={styles.value}>
            £{depositAmount.toLocaleString("en-GB", { minimumFractionDigits: 2 })}
            {depositProtectionScheme && ` (Protected by ${depositProtectionScheme})`}
          </Text>
        </View>
      )}

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.label}>TERMS AND CONDITIONS</Text>
        <Text style={styles.value}>
          This is a template tenancy agreement. Standard terms and conditions should be added here, including:
        </Text>
        <Text style={styles.value}>• Rent payment terms and methods</Text>
        <Text style={styles.value}>• Tenant obligations and responsibilities</Text>
        <Text style={styles.value}>• Landlord obligations and responsibilities</Text>
        <Text style={styles.value}>• Property maintenance and repairs</Text>
        <Text style={styles.value}>• Notice periods for ending the tenancy</Text>
        <Text style={styles.value}>• Restrictions and permitted use</Text>
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.label}>SIGNATURES</Text>
        <Text style={styles.value}>Landlord: _________________________ Date: ___________</Text>
        <Text style={styles.value}>Tenant: _________________________ Date: ___________</Text>
      </View>

      <View style={styles.disclaimer}>
        <Text>
          This document was generated on {new Date().toLocaleDateString("en-GB")} by LandlordLens. 
          Both parties should review and sign this agreement. It is recommended to have this agreement 
          reviewed by a legal professional.
        </Text>
      </View>
    </Page>
  </Document>
)

