/**
 * SUBSCRIPTION SERVICE
 * This service handles all interactions with Stripe for billing and subscriptions.
 * It abstracts away the complexity of the Stripe API from the rest of the application.
 */

const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY); // Initialize Stripe with the secret key
const User = require('../../models/User');
const logger = require('../../lib/logger');

// PRICE IDS
// These map our internal product names (e.g., 'professional_monthly') to the actual Stripe Price IDs.
// These IDs are generated by Stripe when you create products in their dashboard.
const PRICE_IDS = {
    'professional_monthly': process.env.STRIPE_PRICE_PROFESSIONAL_MONTHLY,
    'professional_yearly': process.env.STRIPE_PRICE_PROFESSIONAL_ANNUAL,
    'business_monthly': process.env.STRIPE_PRICE_BUSINESS_MONTHLY,
    'business_yearly': process.env.STRIPE_PRICE_BUSINESS_ANNUAL,
    'enterprise_monthly': process.env.STRIPE_PRICE_ENTERPRISE_MONTHLY,
    'enterprise_yearly': process.env.STRIPE_PRICE_ENTERPRISE_ANNUAL
};

/**
 * Creates a Stripe Checkout Session for a user.
 * This session URL is where the frontend redirects the user to enter payment details.
 * 
 * @param {string} userId - The internal database ID of the user
 * @param {string} tier - The subscription tier (e.g., 'professional')
 * @param {string} period - The billing period ('monthly' or 'yearly')
 * @returns {Promise<Object>} The Stripe session object containing the redirect URL
 */
const createCheckoutSession = async (userId, tier, period) => {
    try {
        const user = await User.findById(userId);
        if (!user) throw new Error('User not found');

        // Look up the correct Stripe Price ID
        const priceId = PRICE_IDS[`${tier}_${period}`];
        if (!priceId) throw new Error('Invalid subscription tier or period');

        // Configure the Checkout Session
        const sessionConfig = {
            mode: 'subscription',
            payment_method_types: ['card'],
            line_items: [{ price: priceId, quantity: 1 }],
            // Where to send the user after successful payment
            success_url: `${process.env.FRONTEND_URL || 'http://localhost:3000'}/dashboard?session_id={CHECKOUT_SESSION_ID}`,
            // Where to send the user if they cancel
            cancel_url: `${process.env.FRONTEND_URL || 'http://localhost:3000'}/pricing`,
            customer_email: user.email,
            client_reference_id: userId, // Used to match the webhook event back to this user
            metadata: { // Custom data to attach to the subscription
                userId: userId,
                tier: tier,
                period: period
            }
        };

        // If user already has a Stripe Customer ID (returning customer), reuse it to avoid duplicates
        if (user.stripeCustomerId) {
            sessionConfig.customer = user.stripeCustomerId;
            delete sessionConfig.customer_email; // Cannot provide both customer ID and email
        }

        const session = await stripe.checkout.sessions.create(sessionConfig);
        return session;
    } catch (error) {
        logger.error('Error creating checkout session', error);
        throw error;
    }
};

/**
 * Creates a Billing Portal Session.
 * This allows users to manage their existing subscription (update card, cancel, view history)
 * hosted by Stripe.
 * 
 * @param {string} userId - The ID of the user requesting the portal
 * @returns {Promise<Object>} The portal session object containing the redirect URL
 */
const createPortalSession = async (userId) => {
    try {
        const user = await User.findById(userId);
        if (!user || !user.stripeCustomerId) throw new Error('User not found or no subscription');

        const session = await stripe.billingPortal.sessions.create({
            customer: user.stripeCustomerId,
            return_url: `${process.env.FRONTEND_URL || 'http://localhost:3000'}/dashboard`,
        });

        return session;
    } catch (error) {
        logger.error('Error creating portal session', error);
        throw error;
    }
};

/**
 * Main Webhook Handler
 * Receives events from Stripe's servers and routes them to the appropriate handler.
 * This is crucial for keeping our database in sync with Stripe.
 * 
 * @param {Object} event - The raw Stripe event object
 */
const handleWebhook = async (event) => {
    switch (event.type) {
        case 'checkout.session.completed':
            // Triggered when a user successfully pays for the first time
            await handleCheckoutCompleted(event.data.object);
            break;
        case 'customer.subscription.updated':
            // Triggered when a subscription renews, changes tier, or cancels
            await handleSubscriptionUpdated(event.data.object);
            break;
        case 'customer.subscription.deleted':
            // Triggered when a subscription completely expires
            await handleSubscriptionDeleted(event.data.object);
            break;
    }
};

/**
 * Handles successful initial payment.
 * Updates the user's record with their new Stripe Customer ID and Subscription details.
 */
const handleCheckoutCompleted = async (session) => {
    const userId = session.client_reference_id;
    const customerId = session.customer;
    const subscriptionId = session.subscription;

    if (userId) {
        // Retrieve full subscription details to get precise dates
        const subscription = await stripe.subscriptions.retrieve(subscriptionId);

        await User.findByIdAndUpdate(userId, {
            stripeCustomerId: customerId,
            stripeSubscriptionId: subscriptionId,
            subscriptionStatus: subscription.status,
            subscription: session.metadata.tier,
            subscriptionPeriod: session.metadata.period,
            subscriptionStartDate: new Date(subscription.current_period_start * 1000), // Convert UNIX timestamp to Date
            subscriptionEndDate: new Date(subscription.current_period_end * 1000)
        });
        logger.info(`Subscription activated for user ${userId}`);
    }
};

/**
 * Handles updates to a subscription (e.g., successful renewal).
 * Keeps subscription status and end dates up to date in our DB.
 */
const handleSubscriptionUpdated = async (subscription) => {
    // Find user by their Stripe Customer ID since we might not have client_reference_id here
    const user = await User.findOne({ stripeCustomerId: subscription.customer });
    if (user) {
        await User.findByIdAndUpdate(user._id, {
            subscriptionStatus: subscription.status,
            subscriptionEndDate: new Date(subscription.current_period_end * 1000)
        });
        logger.info(`Subscription updated for user ${user._id}`);
    }
};

/**
 * Handles subscription cancellation/expiry.
 * Downgrades the user to the 'free' tier in our database.
 */
const handleSubscriptionDeleted = async (subscription) => {
    const user = await User.findOne({ stripeCustomerId: subscription.customer });
    if (user) {
        await User.findByIdAndUpdate(user._id, {
            subscriptionStatus: 'canceled',
            subscription: 'free' // Revert to free tier functionality
        });
        logger.info(`Subscription canceled for user ${user._id}`);
    }
};

module.exports = {
    createCheckoutSession,
    createPortalSession,
    handleWebhook
};
